import express from "express";
import cors from "cors";
import cookieParser from "cookie-parser";
import helmet from "helmet";
import authRoutes from "./routes/auth.routes.js";
import walletRoutes from "./routes/wallet.routes.js";
import tokenRoutes from "./routes/token.routes.js";
import transactionRoutes from "./routes/transaction.routes.js";
import adminRoutes from "./routes/admin.routes.js";
import { errorHandler } from "./middleware/error.js";
import { env } from "./config/env.js";
import { prisma } from "./config/prisma.js";
import { provider } from "./config/blockchain.js";
const app = express(); app.disable("x-powered-by"); app.set("trust proxy", env.trustProxyHops); app.use(helmet()); app.use(cors({ origin: env.frontendUrl, credentials: true })); app.use(express.json({ limit: "20kb" })); app.use(cookieParser());
app.get("/api/health", async (_req, res) => { try { await Promise.all([prisma.$queryRaw`SELECT 1`, provider.getBlockNumber()]); res.json({ status: "ok", database: true, ethereum: true, network: "sepolia", chainId: 11155111 }); } catch { res.status(503).json({ status: "unavailable", database: false, ethereum: false, network: "sepolia", chainId: 11155111 }); } });
app.use("/api/auth", authRoutes); app.use("/api/wallet", walletRoutes); app.use("/api/token", tokenRoutes); app.use("/api/transactions", transactionRoutes); app.use("/api/admin", adminRoutes); app.use(errorHandler); export default app;
