import { Check, Copy, X } from "lucide-react";
import { useState, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode } from "react";
import { shortAddress } from "../../utils/format";

export function Button({ className = "", children, ...props }: ButtonHTMLAttributes<HTMLButtonElement>) { return <button className={`inline-flex cursor-pointer items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-violet-500 to-indigo-500 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-violet-950/20 transition-all duration-200 hover:-translate-y-0.5 hover:brightness-110 hover:shadow-violet-500/20 active:translate-y-0 active:scale-[.98] focus:outline-none focus:ring-2 focus:ring-violet-400 focus:ring-offset-2 focus:ring-offset-[#080a0f] disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:translate-y-0 ${className}`} {...props}>{children}</button>; }
export function Input({ className = "", ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input className={`w-full rounded-xl border border-white/10 bg-white/[.035] px-3.5 py-3 text-sm text-white outline-none transition placeholder:text-white/30 hover:border-white/20 focus:border-violet-400 focus:ring-2 focus:ring-violet-500/20 ${className}`} {...props} />; }
export function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-white/10 bg-[#10141d] ${className}`}>{children}</section>; }
export function Skeleton({ className = "" }: { className?: string }) { return <div aria-hidden="true" className={`skeleton rounded-2xl ${className}`} />; }
export function Badge({ children, tone = "violet" }: { children: ReactNode; tone?: "violet" | "green" | "red" | "amber" }) { const colors = { violet: "border-violet-400/20 bg-violet-400/10 text-violet-200", green: "border-emerald-400/20 bg-emerald-400/10 text-emerald-300", red: "border-red-400/20 bg-red-400/10 text-red-300", amber: "border-amber-400/20 bg-amber-400/10 text-amber-200" }; return <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-medium ${colors[tone]}`}>{children}</span>; }
export function CopyButton({ value, compact = false }: { value: string; compact?: boolean }) { const [copied, setCopied] = useState(false); const copy = async () => { await navigator.clipboard.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }; return <button onClick={copy} aria-label="คัดลอก Wallet Address" title="คัดลอก" className="rounded-lg p-2 text-white/50 transition-all hover:scale-105 hover:bg-white/10 hover:text-white active:scale-95 focus:outline-none focus:ring-2 focus:ring-violet-400">{copied ? <Check size={17} className="text-emerald-400" /> : <Copy size={17} />}{!compact && <span className="sr-only">คัดลอก</span>}</button>; }
export function AddressDisplay({ address }: { address: string }) { return <div className="flex min-w-0 items-center rounded-xl border border-white/10 bg-black/20 px-3 transition hover:border-white/20"><code className="min-w-0 flex-1 truncate text-sm text-white/80">{shortAddress(address)}</code><CopyButton value={address} compact /></div>; }
export function PageHeader({ eyebrow, title, detail, action }: { eyebrow: string; title: string; detail?: string; action?: ReactNode }) { return <header className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[.18em] text-violet-300">{eyebrow}</p><h1 className="text-2xl font-semibold tracking-tight text-white">{title}</h1>{detail && <p className="mt-1 text-sm text-white/50">{detail}</p>}</div>{action}</header>; }
export function EmptyState({ title, body, action }: { title: string; body: string; action?: ReactNode }) { return <div className="flex min-h-52 flex-col items-center justify-center px-6 text-center"><div className="mb-4 grid size-12 place-items-center rounded-2xl bg-violet-500/10 text-xl text-violet-200">◈</div><h3 className="font-medium text-white">{title}</h3><p className="mt-1 max-w-sm text-sm text-white/45">{body}</p>{action && <div className="mt-5">{action}</div>}</div>; }
export function ConfirmModal({ open, title, children, onClose, onConfirm, busy }: { open: boolean; title: string; children: ReactNode; onClose: () => void; onConfirm: () => void; busy?: boolean }) { if (!open) return null; return <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm" onMouseDown={onClose}><div className="w-full max-w-md animate-[modal-in_.18s_ease-out] rounded-2xl border border-white/10 bg-[#141923] p-6 shadow-2xl" onMouseDown={(event) => event.stopPropagation()}><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold text-white">{title}</h2><button aria-label="ปิด" onClick={onClose} className="rounded-lg p-1 text-white/50 transition hover:bg-white/10 hover:text-white focus:outline-none focus:ring-2 focus:ring-violet-400"><X size={20} /></button></div>{children}<div className="mt-6 flex justify-end gap-3"><Button onClick={onClose} className="bg-white/10 shadow-none hover:bg-white/15">ยกเลิก</Button><Button disabled={busy} onClick={onConfirm}>{busy ? "กำลังส่ง..." : "ยืนยันการส่ง"}</Button></div></div></div>; }
export function TransactionStatusBadge({ status }: { status: string }) { return <Badge tone={status === "SUCCESS" ? "green" : status === "FAILED" ? "red" : "amber"}>{status === "SUCCESS" ? "สำเร็จ" : status === "FAILED" ? "ล้มเหลว" : "กำลังดำเนินการ"}</Badge>; }
